openapi: 3.0.3
info:
  title: Juice shop API documentation
  version: 0.5.0

servers:
  - url: http://192.168.64.4:3000

tags:
  - name: Login
    description: Login a user
paths:
  /rest/user/login:
    post:
      tags:
        - Login
      summary: Login a user
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: test@admin.se
                password:
                  type: string
                  example: asjd90asjd90
      responses:
        '200':
          description: 'Successfully signed in'
          content:
            application/json:
              schema:
                type: object
                properties:
                  authentication:
                    type: object
                    properties:
                      token:
                        type: string
                      umail:
                        type: string
